### ISSUE TITLE
バーコードのダイアログに閉じるボタンをつけてほしい

### ISSUE THREAD

**Issue by rokka032486** [teritamahamburg/asemana#1]
どちらかに
![barcode_create_2](https://user-images.githubusercontent.com/20470319/68917204-9c85b880-07ac-11ea-91d2-fef99b710eed.png)

**Comment by syuchan1005** [comment]
@rokka032486 右左どっちがいいですか

一応Material Design的には ( https://material.io/components/dialogs/ )
画面下部につけることになってる

**Comment by rokka032486** [comment]
準拠してください

**Comment by syuchan1005** [comment]
@rokka032486 こんなのどうですか

![image](https://user-images.githubusercontent.com/8733829/68917707-d5269180-07ae-11ea-9f92-72f6ebc8dd0b.png)

**Comment by rokka032486** [comment]
バーコードの上の余白をもう少し
CLOSEをもっとボタンらしく

**Comment by syuchan1005** [comment]
@rokka032486 どうですか

![image](https://user-images.githubusercontent.com/8733829/68917789-220a6800-07af-11ea-8f2f-091058b703a0.png)

![image](https://user-images.githubusercontent.com/8733829/68917880-6bf34e00-07af-11ea-94e8-465676fc90c2.png)

**Comment by rokka032486** [comment]
上がよくない原因はわからない
下は、テキストボックスをもう少し小さくして左寄せ、その右にTRANSFER。
ダイアログの下のほうにCLOSE。
